source "http://rubygems.org"
gem "rake"
gem "cucumber", ">0.0"
gem "rspec", ">0.0"
gem "watir-webdriver"
gem "cuporter", ">0.0"
gem "headless", ">0.0"
gem "yard-cucumber"
gem "rdiscount"
gem "prawn"
gem "pry"
gem "net-ssh"
gem 'page-object'
gem 'browsermob-proxy'
gem "rb-readline"
gem "webdriver-user-agent"
gem "faker"
gem "quoth"
gem "net-ssh"
gem "net-scp"
gem "rest-client"
gem "nokogiri", '~> 1.5.9'
gem "watir-dom-wait"
